name: "AI Code Reviewer"
description: "Perform code reviews and comment on diffs with your own rules using OpenAI API."
inputs:
  GITHUB_TOKEN:
    description: "GitHub token to interact with the repository."
    required: true
  OPENAI_API_KEY:
    description: "OpenAI API key for GPT."
    required: true
  OPENAI_API_MODEL:
    description: "OpenAI API model."
    required: false
    default: "gpt-4o"
runs:
  using: "node22"
  main: "dist/index.js"
branding:
  icon: "aperture"
  color: "green"
