global: 
  - "No console.logs allowed."

extensions:
  - file_extensions: [".ts", ".js"]
    rules:
      - "Always use export default"
  - file_extensions: [".exs", ".ex"]
    rules:
      - "If adding foreign keys, ensure appropriate indexes are added"
      - "Verify index type is appropriate for the use case"
      - "Consider if unique index is needed"
      - "Ensure table names are pluralized"
      - "For data migrations, include testing strategy"
      - "New tables must use UUID as primary key"
      - "Include timestamps (inserted_at, updated_at)"
      - "Column removals must have all usages removed in previous PR"
  - file_extensions: [".tsx"]
    rules:
      - "Always use arrow functions"

directories: 
  - paths: ["*Consumer.ex"]
    rules:
      - "Update catalog-info.yaml"
      - "Add schema to events schemas"
  - paths: ["*Publisher.ex"]
    rules:
      - "Update catalog-info.yaml"
      - "Add schema to events schemas"
  - paths: ["**/context/**"]
    rules:
      - "Include comprehensive tests"
  - paths: ["**/resolvers/**"]
    rules:
      - "Use GraphQL fragments for leaf components"
  - paths: ["**/scripts/**"]
    rules:
      - "Include tests for complex scripts"
      - "Use transactions appropriately"
  - paths: ["**/schemas/**"]
    rules:
      - "Handle constraints in changesets"
      - "Validate all required fields"
      - "Consider custom validation types"
      - "Evaluate Postgres Enum usage where appropriate"
  - paths: ["**/system_prompt/**"]
    rules:
      - "Create new version when modified"
      - "Verify all variables are provided for rendering"
      - "Update DB table with new prompt"
  - paths: ["**/lib/**"]
    rules:
      - "Use pattern matching effectively"
      - "Break complex functions into smaller ones"
      - "Follow Elixir naming conventions"
      - "Simplify with/case statements using pattern matching"
      - "Maintain immutability principles"
      - "Use Enum and Stream appropriately"
      - "Choose appropriate data structures"
      - "Consider recursive function performance"
      - "Handle long-running processes with Task/GenServer"
      - "Use destructuring where beneficial"
  - paths: ["**/e2e/**"]
    rules:
      - "New user flows must have e2e test coverage"

ignore:
  - ".git"
  - "node_modules"
  - "dist"
  - "build" 
  - "_build" 
  - "csv" 
  - "json"